### ISSUE TITLE
Request to update Vizgen Cell Boundaries Polygon generation

### ISSUE THREAD

**Issue by rushin682** [YangLabHKUST/UCS#3]
Hello,

Thank you for a great repo and paper! 

We noticed that for Vizgen aspect, creating of polygons (Line 140 - 152: preprocess/vizgen.py) uses the old cell boundaries h5 format. However, we have a parquet file for the cell boundaries. Is it possible to add a feature that can take the parquet file as input to create the polygons as well?

Thanks once again for your time. Looking forward to your response.

best,
Rushin

**Comment by chenyhvvvv** [comment]
Thank you for your interest! Can you show me a public dataset to let me try on it?

**Comment by devianggr** [comment]
Hi, 

Maybe I can help Rushin to share the public dataset with the cell_boundaries.parquet file.
You can download the access dataset through this link:
https://info.vizgen.com/protein-co-detection-showcase?submissionGuid=2e012b62-62b4-4a7e-97d4-cbfbd0a7a903

Best,
Devi

**Comment by chenyhvvvv** [comment]
Hi, after trying and searching for reading parquet object of Vizgen, I can not find a proper package or code to read it. Directly using pandas can not work.
<img width="1110" alt="image" src="https://github.com/user-attachments/assets/1fbc0e22-51db-43e3-9067-dac636529f65">
And there is little result of this and still an issue in https://github.com/satijalab/seurat/issues/7080.

But instead, you can use Cellpose to segment the MIP DAPI image. The code include `prepare_dapi_for_cellpose` in `preprocess/vizgen.py` to provide MIP image of `mosaic_DAPI_z[].tif` and segment using script like

`python preprocess/cellpose_dapi.py --dapi ./data/vizgen_mouse_brain/mosaic_DAPI_mip_resized.tif --out_dir ./data/vizgen_mouse_brain`
