### ISSUE TITLE
Error in scvi version when running the downstream process (analyse.py)

### ISSUE THREAD

**Issue by devianggr** [YangLabHKUST/UCS#4]
Hi,

Thanks for providing the repo!

Currently, I am doing segmentation of my Vizgen and Xenium datasets. And I am curious about the downstream process you provided in this repo. However, when I wanted to run the analyse.py, I encountered a problem, especially with the scvi version.

DeprecationWarning: scvi is deprecated, please uninstall scvi via `pip uninstall scvi` and install the new scvi-tools package at github.com/YosefLab/scvi-tools
  warnings.warn(deprecation_msg, DeprecationWarning)

In this case, I have even tried to install a new scvi-tools, however, it led again to another error : ImportError: cannot import name 'AlignedViewMixin' from 'anndata._core.aligned_mapping'

Since I am not so familiar with bioinformatic analysis, it would be nice if you could help solve this issue.

Thanks again for considering my issue! I am looking forward to your response.

Best regards,
Devi

**Comment by chenyhvvvv** [comment]
Hi, have you followed the instruction to install UCS? You can try to reinstall UCS and ignore the warning and then try to run the notebook.

**Comment by devianggr** [comment]
Hi, 

thanks for the suggestion!
I reinstalled everything, and still, the same problem occurred
![image](https://github.com/user-attachments/assets/3260aa3a-bc93-4d16-a19f-9a8b802d02c6)

Best,
Devi

**Comment by chenyhvvvv** [comment]
Yes! This problem actually exists. I will try to solve it and reply.

**Comment by chenyhvvvv** [comment]
By isntall:

pip install scvi_tools=1.1.2
pip install anndata=0.10.8

The error disappears. Can you try?

**Comment by chenyhvvvv** [comment]
Try to reinstall scvi and anndata:
pip install scvi_tools==1.1.2
pip install anndata==0.10.8
